simulation:
  length: 600   # Length in seconds of each simulation
  resolution: 1 # Time in seconds to calculate each value
  multiplier: 0.05 # Time multiplier (allows for 'slow-motion')
  type: c172

environmental:
  visibility: 100
  terrain: 2 # scale of 1 to 6, how much the elevation height changes

failure:
  - None
  - intakemassflowrate # blockage; intake mass flow stops, thrust declines, transpondercode 7700
  - fuellevels # leak; fuel levels drop
  - oillevels # leak; engine temperature rises
  - enginerpm # failure; thrust drops, transpondercode 7700
  - enginetemperature # overheat; thrust drops, transpondercode 7700 
  - propellerrpm # strike; thrust declines, transpondercode 7700 
  - batterylevels # outage; battery levels drop, transpondercode 7700 
  - communicationsdelay # lost; transpondercode 7600 
  - None # lost; no data reported
  - radarproximity # breach; no data reported
  - fuselagestress # decompression; thrust drops, transpondercode 7700
  - None # wing lost; thrust drops, transpondercode 7700
  - None # wing lost; elevator drops, transpondercode 7700
  - None # control surface lost; elevator drops, transpondercode 7700
  - engineloading # engine lost; thrust drops, transpondercode 7700

model:
  propulsion:
    - intakemassflowrate
    - fuellevels
    - oillevels
    - enginerpm
    - enginetemperature
    - propellerrpm
  electrical: 
    - batterylevels
    - alternatoroutput
  avionics:
    - communicationsdelay
    - satellitemonitoring
    - radarproximity
    - transpondercode
  airframe:
    - fuselagestress
    - wingstress
    - tailstress
    - controlsurfaceloading
    - engineloading

controls:
  - throttle
  - primaryswitch
  - secondaryswitch
  - elevator

instrumentation:
  - airspeed
  - altitude
  - pitch

c172:
  mass: 757
  aspectratio: 7.32
  surfacearea: 15.98
  parasitedrag: 0.029
  propellerarea: 2.843
  propellervelocity: 58.572
  fuelefficiency: 0.2
  intakearea: 0.8
  defaults:
    throttle: 0.462
    angleofattack: 4.768
    airspeed: 41.7337
    enginerpm: 2400
    intakemassflowrate: 20
